#!/usr/bin/env bash
# script to install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "It's Elvis K from Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
